'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export default function SignUp() {
  const router = useRouter(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  async function submit(e: React.FormEvent) { e.preventDefault(); const result = await authClient.signUp.email({ name, email, password }); if (result.error) setError('No pudimos crear la cuenta. Probá con otros datos.'); else { router.push('/'); router.refresh() } }
  return <main className="auth-page"><section className="auth-aside"><div className="auth-brand"><span className="brand-mark">◎</span> Casa Clara</div><div><p className="auth-kicker">TU CASA, EN ORDEN</p><h2>Una forma más tranquila de llevar las cuentas.</h2><p className="auth-aside-copy">Creá tu cuenta, invitá a las personas de tu hogar y empiecen juntos.</p></div><div className="auth-aside-footer"><span className="auth-dot" /> Todos tienen el mismo poder</div></section><form className="auth-card" onSubmit={submit}><div className="auth-mobile-brand"><span className="brand-mark">◎</span> Casa Clara</div><div className="auth-kicker">EMPEZÁ EN UN MINUTO</div><h1>Creá tu cuenta</h1><p className="auth-intro">Después podés crear un grupo e invitar a tu hogar.</p><div className="auth-fields"><label>Nombre<input placeholder="Damián o Eli" required value={name} onChange={e => setName(e.target.value)} /></label><label>Email<input type="email" placeholder="vos@ejemplo.com" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Contraseña<input type="password" placeholder="Mínimo 8 caracteres" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} /></label></div>{error && <p className="auth-error">{error}</p>}<button className="auth-submit" type="submit">Crear cuenta <span>→</span></button><p className="auth-switch">¿Ya tenés cuenta? <a href="/sign-in">Ingresá</a></p></form></main>
}
